language: node_js
node_js: lts/*
services:
  - docker
branches:
  only:
    - master
before_install:
  - openssl aes-256-cbc -K $encrypted_d8b91d35f06e_key -iv $encrypted_d8b91d35f06e_iv
    -in budget-service/.env.enc -out budget-service/.env -d
  - openssl aes-256-cbc -K $encrypted_e51ccb9a6155_key -iv $encrypted_e51ccb9a6155_iv
    -in frontend/.env.enc -out frontend/.env -d
  - cd budget-service
install: yarn
before_script: yarn build
script: yarn test
before_deploy: cd ..
deploy:
  provider: script
  script: bash budget-service/script/deploy.sh
  skip_cleanup: true
  on:
    branch: master
