language: node_js
node_js: lts/*
services:
  - docker
branches:
  only:
    - master
before_install:
  - openssl aes-256-cbc -K $encrypted_3c84dcdc6bbe_key -iv $encrypted_3c84dcdc6bbe_iv
    -in budget-service/.env.enc -out budget-service/.env -d
  - openssl aes-256-cbc -K $encrypted_e51ccb9a6155_key -iv $encrypted_e51ccb9a6155_iv
    -in frontend/.env.enc -out frontend/.env -d
install: yarn
before_script:
  - cd frontend
  - yarn test
  - cd ../budget-service
  - yarn test
script: yarn build
before_deploy: cd ..
deploy:
  provider: script
  script: bash budget-service/script/deploy.sh
  skip_cleanup: true
  on:
    branch: master
