version: "3"
services:
  web:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    links:
      - frontend
    volumes:
      - "./docker/volumes/nginx/nginx.conf:/etc/nginx/conf.d/default.conf"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - "./frontend:/app/frontend"
      - "/app/frontend/node_modules"

  budget-service:
    build:
      context: ./budget-service
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    volumes:
      - "./budget-service:/app/budget-service"
      - "./docker/volumes/budget-service/.env:/app/budget-service/.env"
      - "/app/budget-service/node_modules"
